Create README_6.md
TomMonaco27/django pull request #6
Opened 2021-06-17 09:10 UTC by TomMonaco27

2021-06-17 16:30 UTC, Vokler requested changes

2021-06-17 16:30 UTC, Vokler commented on users/views.py
> +            'baskets': Basket.baskets,
Это же у вас не classmethod методы, как вы к ним так обращаетесь?) Они работают?

2021-06-17 16:33 UTC, Vokler commented
По поводу другой реализации корзины товаров
https://pocoz.gitbooks.io/django-v-primerah/content/glava-7-sozdanie-internet-magazina/sozdanie-korzini/hranenie-korzini-pokupok-v-sessiyah.html

2021-06-17 21:01 UTC, TomMonaco27 commented on users/views.py
> +            'baskets': Basket.baskets,
да вы правы...видимо не запушилось...

2021-06-18 07:22 UTC, Vokler approved these changes

2021-06-18 07:22 UTC, merged